name: 每日签到（server酱通知）

on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:

jobs:
  daily-checkin:
    runs-on: ubuntu-latest

    steps:
    - name: 获取信息
      id: get-info
      run: |
        response=$(curl -s -X GET \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.RAINYUN_API_KEY }}" \
          https://api.v2.rainyun.com/user/)
        name=$(echo $response | jq -r '.data.Name')
        points=$(echo $response | jq -r '.data.Points')
        icon_url=$(echo $response | jq -r '.data.IconUrl')
        echo "::set-output name=name::$name"
        echo "::set-output name=points::$points"
        echo "::set-output name=icon_url::$icon_url"

    - name: 发送用戶信息
      run: |
        curl -s -X POST \
        -H 'Content-Type: application/json
          -d '{
          "title": "雨云签到",
          "desp": "尊敬的'"${{ steps.get-info.outputs.name }}"'大人，即将为您签到！当前剩余积分'"${{ steps.get-info.outputs.points }}"'！"
          }' \
          "https://sctapi.ftqq.com/${{ secrets.SERVERCHAN_TOKEN }}.send"

    - name: 发送签到请求
      id: checkin
      run: |
        response=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.RAINYUN_API_KEY }}" \
          -d '{"task_name": "每日签到"}' \
          https://api.v2.rainyun.com/user/reward/tasks)
        echo "::set-output name=response::$response"

    - name: 发送签到结果
      run: |
        curl -s -X POST \
        -H 'Content-Type: application/json
          -d '{
          "title": "雨云签到",
            "desp": "每日签到已完成！\n签到结果: '"${{ steps.checkin.outputs.response }}"'"
          }' \
          "https://sctapi.ftqq.com/${{ secrets.SERVERCHAN_TOKEN }}.send"
