name: 每日签到（Bark通知）

on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:

jobs:
  daily-checkin:
    runs-on: ubuntu-latest

    steps:
    - name: 发送签到请求
      id: checkin
      run: |
        response=$(curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.RAINYUN_API_KEY }}" \
          -d '{"task_name": "每日签到"}' \
          https://api.v2.rainyun.com/user/reward/tasks)
        echo "response=$response" >> $GITHUB_ENV

    - name: 获取信息
      id: get-info
      run: |
        response=$(curl -s -X GET \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.RAINYUN_API_KEY }}" \
          https://api.v2.rainyun.com/user/)
        name=$(echo $response | jq -r '.data.Name')
        points=$(echo $response | jq -r '.data.Points')
        icon_url=$(echo $response | jq -r '.data.IconUrl')
        echo "name=$name" >> $GITHUB_ENV
        echo "points=$points" >> $GITHUB_ENV
        echo "icon_url=$icon_url" >> $GITHUB_ENV

    - name: 发送通知
      run: |
        curl -s -X POST \
        -H "Content-Type: application/json" \
        -d '{
          "title": "雨云签到",
          "body": "尊敬的'"${{ env.name }}"'大人，每日签到已完成！\n签到结果: '"${{ env.response }}"'，\n当前剩余积分'"${{ env.points }}"'！",
          "group": "雨云签到"
          }' \
          "https://api.day.app/${{ secrets.BarkToken }}/"
